#!/usr/bin/env bash

 arr=()
if [[ $1 -gt 0 ]]
then
	for num in $(eval echo {0..$1})
	do
		arr+=($num)
	done
elif [[ $1 -lt 0 ]]
then
	for num in $(eval echo {$1..0})
	do
		arr+=($num)
	done
fi
echo ${arr[*]}

